### ISSUE TITLE
Listing has been removed

### ISSUE THREAD

**Issue by connorblack** [jonwaller/howtobuybitcoinsinfo-website#190]
Hey guys. First let me start off by saying how much we at Harborly love howtobuybitcoins.info - the devs who brought this together rock!

I was looking over the Canadian listing today (http://howtobuybitcoins.info/ca.html) and, although we have been listed since about the 26th of December and were showing up before, it looks like with subsequent commits/merges we've stopped being rendered out by the program.

Here's our entry - https://github.com/jonwaller/howtobuybitcoinsinfo-website/blob/master/data/services.yaml#L1934

Is there something we did incorrectly with the formatting, or possible another entry has caused an error? For what it's worth, I can't seem to find Igot or Exmo (both below the Harborly entry) on any of the pages they should be listed on either: 

Igot - https://github.com/jonwaller/howtobuybitcoinsinfo-website/blob/master/data/services.yaml#L1954
Exmo - https://github.com/jonwaller/howtobuybitcoinsinfo-website/blob/master/data/services.yaml#L1944

Thanks, and let me know what I can do to help!

**Comment by slick2** [comment]
Hi,

The project owner Jon, would push that to live, once he had a chance.

**Comment by autorius** [comment]
Hi,
How can i list bitcoins service website? I m still dont understand gist
system..

**Comment by connorblack** [comment]
@slick2 Is it possible for listings to get removed with pushes? We were listed all through January and my best guess is that we were removed about a week ago.

**Comment by slick2** [comment]
I do verify first pull request on the files that have been modified, my apologies if your site got delisted, anyways you are to make a new pull request.

**Comment by slick2** [comment]
@autorius please dont hi jack the thread, you are free to make a separate issue.

**Comment by connorblack** [comment]
Hi,

The listing that I added 29 days ago still is not showing up on the Canadian page (http://howtobuybitcoins.info/ca.html).

Is there anything needed on my end?

Thanks

**Comment by slick2** [comment]
Our apologies. it would be updated on the next site update
