### ISSUE TITLE
Add FoxBit (Brazilian Exchange)

### ISSUE THREAD

**Issue by schiavonxv** [jonwaller/howtobuybitcoinsinfo-website#206]
foxbit:
  label: FoxBit
  url: http://www.foxbit.com.br
  location: [br]
  countries: [br]
  icon: http://foxbit.com.br/favicon.png
  content: |
      <p>Buy and sell bitcoins in Brazil.</p>
  coins: [btc]

**Comment by slick2** [comment]
please fork and add those information on services.yaml
