### ISSUE TITLE
AU updates

### ISSUE THREAD

**Issue by aussiehash** [jonwaller/howtobuybitcoinsinfo-website#226]
**Coinjar**'s fee is now a flat 1%
https://blog.coinjar.com/2015/05/06/we-halved-our-buy-fee/

**Cointree** is dead
they're showing an old bitcoin price, and attempting to buy results in

    We are not accepting purchases at the moment. See our blog for more information.

Their blog has not been updated, and makes no mention of them not accepting purchases.

**Independent Reserve** should be added (they accept AUD / USD / NZD)
https://www.independentreserve.com/Help#fees

**Comment by slick2** [comment]
Can you fork, put those updates and make a pull request.
